import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarMain from "@/components/NavBarMain";
import Footer from "./Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBarMain />
        <h1 className="text-center text-blue-700 font-bold">
          มหาลัยเอเชียอาคเนย์
        </h1>
        <hr className="my-10 w-3/4 m-auto" />
        
        {children}

        <Footer/>

        <hr className="my-10" />
        <h5 className="text-center">Created By Mint SAU </h5>
      </body>
    </html>
  );
}
